name: suncalc
description: A port of the suncalc library from https://github.com/mourner/suncalc
version: 0.1.0
author: Cyril Moralès <palmsnipe@gmail.com>
homepage: https://github.com/palmsnipe/suncalc

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
